---
title: "Website dataset workflow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Website dataset workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---





The Pandemic PACT data is publicly available for download from its [website](https://www.pandemicpact.org/). `{pactr}` provides an application programming interface (API) to the research programme's dataset available from its website data download facility allowing for programmatic access to its publicly available funder tracker dataset.

## Website data interface

The functions for interfacing with the data available from the Pandemic PACT website allow for *downloading*, *reading*, and *processing*. Current website data-specific functionalities available in `{pactr}` are:

1. Downloading of Pandemic PACT dataset available from the website (*stable*);

2. Reading of Pandemic PACT dataset available from the website (*stable*); and,

3. Processing of Pandemic PACT dataset available from the website (*experimental*).

## Website data workflow


```
#> Warning in readLines("website.mmd"): incomplete final line found on
#> 'website.mmd'
#> Error in loadNamespace(name): there is no package called 'webshot'
```

### Download data available from website

To download the Pandemic PACT tracker dataset available from its website, the following command can be used:


```r
## Save the dataset from website to a temporary directory ----
pact_download_website(path = tempdir())
```

which will return the path to the downloaded dataset:


```
#> [1] "/tmp/RtmpjUmn8P/pandemic-pact-grants.csv"
```

### Read the Pandemic PACT tracker dataset from the website

Instead of downloading, the Pandemic PACT dataset available from its website can be read into R directly as follows:


```r
pact_read_website()
```

which results in the following:


```
#> # A tibble: 9,862 × 39
#>    GrantID PubMedGrantId GrantTitleEng Abstract PublicationYearOfAward
#>    <chr>   <list>        <chr>         <chr>                     <int>
#>  1 C00037  <chr [1]>     COVID-19: Im… "The cl…                   2020
#>  2 C00038  <chr [3]>     Identificati… "The ou…                   2020
#>  3 C00040  <chr [2]>     Development … "This r…                   2020
#>  4 C00041  <chr [1]>     Rapid, Low-c… "The ou…                   2020
#>  5 C00043  <chr [1]>     Rapid Resear… "In 201…                   2020
#>  6 C00045  <chr [1]>     Development … "Corona…                   2020
#>  7 C00046  <chr [2]>     Rapid develo… "The ou…                   2020
#>  8 C00047  <chr [1]>     Preventing S… "The SA…                   2020
#>  9 C00048  <chr [1]>     Understandin… "A new …                   2020
#> 10 C00049  <chr [2]>     RIsk of envi… "This s…                   2020
#> # ℹ 9,852 more rows
#> # ℹ 34 more variables: GrantEndYear <int>,
#> #   ResearchInstitutionName <chr>, GrantAmountConverted <dbl>,
#> #   StudySubject <list>, Ethnicity <list>, AgeGroups <list>,
#> #   Rurality <list>, VulnerablePopulations <list>,
#> #   OccupationalGroups <list>, StudyType <list>,
#> #   ClinicalTrial <list>, Pathogen <list>, InfluenzaA <chr>, …
```

### Process the Pandemic PACT tracker dataset from the website

The package includes functions that will process the Pandemic PACT tracker dataset into specific structures and aggregations that will allow for further plotting and reporting of similar outputs that are currently presented in the Pandemic PACT website.

For example, the following will process the Pandemic PACT tracker dataset into an aggregated dataset structure that can be used to create a similar plot to the one presented in the [website](https://www.pandemicpact.org/visualise#disease).


```r
pact_read_website() |>
  pact_process_website_topic_group(topic = "Disease", group = "GrantStartYear")
```

which produces the following output:


```
#> # A tibble: 170 × 3
#>    GrantStartYear Disease                                      n
#>             <int> <chr>                                    <int>
#>  1           1978 Pandemic-prone influenza                     1
#>  2           1978 Severe Acute Respiratory Syndrome (SARS)     1
#>  3           1981 COVID-19                                     1
#>  4           1982 COVID-19                                     1
#>  5           1988 COVID-19                                     1
#>  6           1992 COVID-19                                     6
#>  7           1994 COVID-19                                     2
#>  8           1996 COVID-19                                     1
#>  9           1997 COVID-19                                    28
#> 10           1997 Zika virus disease                           1
#> # ℹ 160 more rows
```
